name = "NESAPOceananigans"
uuid = "39df175f-fbd4-440a-99a6-d607917340a7"
authors = ["Simone Silvestri"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
